{% set name = "db-to-sqlite" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/db-to-sqlite-{{ version }}.tar.gz
  sha256: 1d6ca66287ac53bddd7515197cea58480d2d4673ced8e5c8d3e05c6ec1e84be9

build:
  entry_points:
    - db-to-sqlite = db_to_sqlite.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - sqlalchemy
    - sqlite-utils >=2.9.1
    - click

test:
  imports:
    - db_to_sqlite
  commands:
    - pip check
    - db-to-sqlite --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://datasette.io/tools/db-to-sqlite
  summary: CLI tool for exporting tables or queries from any SQL database to a SQLite file
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
